name: RulesUI
version: 0.0.1
main: creeperplayer20\RulesUI\Main
author: creeperplayer20
api: 4.0.8
src-namespace-prefix: creeperplayer20\RulesUI

commands:
    rules:
        description: "Server rules"
        usage: "/rules"
        permission: "rules.command"
permissions:
    rules.command:
        default: op
